name: Run JMeter Script

on:
  schedule:
    - cron: '0 1-23 * * *'
    - cron: '0 0 * * *'

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run JMeter
      uses: justb4/jmeter-action@main
      with:
        scriptPath: https://github.com/MohamedSci/SimpleBooksAPIJMeterCollection/blob/main/BookApiPerformanceTestingPlan.jmx
        propertiesFile: https://github.com/MohamedSci/SimpleBooksAPIJMeterCollection/blob/main/jmeter.properties
